# Hugo variables
#
baseURL = "http://192.168.1.32/"
languageCode = "en-us"
title = "jgarfield.com"
theme = "hugo-theme-jgarfield"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# optionally override the site's footer with custom copyright text
#copyright = "© <a href=\"https://github.com/Tri4ce\">Justin Garfield</a> 2017"
#googleAnalytics = "UA-123-45"
#disqusShortname = "XYW"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.navigation]]
weight = 1
name = "Articles"
url = "/post"

[[menu.navigation]]
weight = 2
name = "Projects"
url = "/projects"
identifier = "projects"

	[[menu.navigation]]
	parent = "projects"
	weight = 1
	name = "Gaming"
	url = "/projects/gaming"
	identifier = "projects-gaming"

		[[menu.navigation]]
		parent = "projects-gaming"
		weight = 1
		name = "Blood of Sargeras Multi-purchase"
		url = "/projects/gaming/blood-of-sargeras-multi-purchase"

	[[menu.navigation]]
	parent = "projects"
	weight = 2
	name = "Programming"
	url = "/projects/programming"
	identifier = "projects-programming"

		[[menu.navigation]]
		parent = "projects-programming"
		weight = 1
		name = "cppOS"
		url = "/projects/programming/cppos"

	[[menu.navigation]]
	parent = "projects"
	weight = 3
	name = "Web"
	url = "/projects/web"
	identifier = "projects-web"

		[[menu.navigation]]
		parent = "projects-web"
		weight = 1
		name = "jgarfield.com"
		url = "/projects/web/jgarfield-com"

[[menu.navigation]]
weight = 3
name = "About"
url = "/about"
identifier = "about"

	[[menu.navigation]]
	parent = "about"
	weight = 1
	name = "Career"
	url = "/about/career"

	[[menu.navigation]]
	parent = "about"
	weight = 2
	name = "My Technology Profile"
	url = "/about/technology-profile"

	[[menu.navigation]]
	parent = "about"
	weight = 3
	name = "My PCs and Hardware"
	url = "/about/pcs-and-hardware"

[[menu.navigation]]
weight = 4
name = "Contact"
url = "/contact"


# Theme variables
#
[params]

  # Site author
  author = "Justin Garfield"

  # Description/subtitle for homepage (can be Markdown)
  description = "The musings of a software engineer."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  useCustomNavigation = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  [params.sidebar]
    
    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "username"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et


PygmentsCodeFences=true
